### PR TITLE
53 move social media icons to footer

### PR DESCRIPTION
**Pull request by iiinnnaaa**

### CODE REVIEW

**Comment by leo72** [comment]
Something wrong here, @iiinnnaaa . This PR contains @iiinnnaaa
"Add Josef Sans font family, drupal color palette and gulpfile..." and "Add lando file" commits.
Please create a branch from master.

**Comment by leo72** [comment]
This branch has conflicts that must be resolved, @iiinnnaaa

**Comment by iiinnnaaa** [comment]
Can you please check this again @leo72, thanks!

**Comment by levmyshkin** [comment]
I had the problem with Kint missing module, so I added custom module Kint without any functionality. It can be removed after all PRs merged

**Comment by iiinnnaaa** [comment]
Ready @leo72 , I've changed the logo and merged branches

**Pull request merged**
